server:
  port: 19370
      
spring:
  application:
    name: service-a
  main:
    allow-bean-definition-overriding: true
#  cloud:
#    config: 
#      uri: http://127.0.0.1:19671
      
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
#   instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:19270/eureka/}
      
serviceWorker:
  config: '{
             "name" : "API-ACCU-WEATHER-V1-FORECAST_DAILY",
             "type" : "single",
             "config" : {
               "scheme" : "https",
               "host" : "api.accuweather.com",
               "method" : "GET",
               "requestRule" : [
                 {
                   "condition" : [],
                   "action" : {
                     "path" : "forecasts/v1/daily/FUNCTION( , headers, x-api-weather-forecast-days)day/FUNCTION( , headers, x-api-weather-location-key)",
                     "headers" : null,
                     "queryParams" : {
                       "apiKey" : "",
                       "languag" : "FUNCTION( , headers, x-api-languag)",
                       "details" : true,
                       "metric" : true
                     },
                     "requestBody" : null
                   }
                 }
               ],
               "responseRule" : [
                 {
                   "condition" : ["TRIGGER(responseStatus, code, 404)"],
                   "responseBody" : {
                     "code" : 404,
                     "message" : "error_message_404"
                   }
                 },
                 {
                   "condition" : ["TRIGGER(responseStatus, code, 200)"],
                   "responseBody" : {
                     "code" : "FUNCTION( , responseStatus, code)",
                     "message" : "sucess",
                     "ret" : "FUNCTION( , responseBody, $)"
                   }
                 }
               ]
             }
           }'