server:
  port: 19371
      
spring:
  application:
    name: service-b
  main:
    allow-bean-definition-overriding: true
#  cloud:
#    config: 
#      uri: http://127.0.0.1:19671
      
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
#   instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:19270/eureka/}