server:
  port: 19271
  ## reference for server.pfx : https://great-developer.tistory.com/91
#  ssl:
#    enabled: true
#    key-store: server.pfx
#    key-store-type: PKCS12
#    key-store-password: qe71w46d03b1
#    key-password: qe71w46d03b1
      
## https://twofootdog.tistory.com/64
spring:
  application:
    name: service_gateway
  main:
    allow-bean-definition-overriding: true
#  cloud:
#    config: 
#      uri: http://127.0.0.1:19671

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # default false
      routes:
#        - id: service-a
#          uri: http://localhost:19370
#          predicates:
#            - Path=/**
#            - Header=x-api-service, serviceA
#        - id: service-b
#          uri: lb://service-b
#          predicates:
#            - Path=/**
#            - Header=x-api-service, serviceB
#        - id: openapi
#          uri: lb://service-b
#          predicates:
#            - Path=/v3/api-docs/**
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v2/api-docs
      

## reference : https://springboot.cloud/26
## reference : https://www.baeldung.com/spring-cloud-custom-gateway-filters
## reference : https://shining-life.tistory.com/53
## reference : https://piotrminkowski.wordpress.com/2020/02/20/microservices-api-documentation-with-springdoc-openapi/
## reference : https://kouzie.github.io/spring/%EC%8A%A4%ED%94%84%EB%A7%81-%ED%81%B4%EB%9D%BC%EC%9A%B0%EB%93%9C-gateway/#spring-cloud-gateway
## reference : https://dev-pengun.tistory.com/entry/Spring-Boot-CORS-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0

## https://lion-king.tistory.com/m/entry/Spring-Boot-Spring-Cloud-MSA-3-Eureka%EB%9E%80-%EC%A0%81%EC%9A%A9%EB%B0%A9%EB%B2%95?category=855644
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
#   instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:19270/eureka/}
      
route:
  config: '{"configs" : [ { "serviceName" : "service-a", "enable" : true, "path" : "/service-a/**", "routingUri" : "http://localhost:19370", "openApiPath" : "/v3/api-docs/service-a", "swaggerPath" : "/v2/api-docs" }, { "serviceName" : "service-b", "enable" : true, "path" : "/service-b/**", "routingUri" : "http://localhost:19371", "openApiPath" : "/v3/api-docs/service-b", "swaggerPath" : "/v2/api-docs" } ] }'
#  config: '{"configs" : [ { "serviceName" : "service-a", "enable" : true, "path" : "/service-a/**", "routingUri" : "lb://service-a", "openApiPath" : "/v3/api-docs/service-a", "swaggerPath" : "/v2/api-docs" }, { "serviceName" : "service-b", "enable" : true, "path" : "/service-b/**", "routingUri" : "lb://service-b", "openApiPath" : "/v3/api-docs/service-b", "swaggerPath" : "/v2/api-docs" } ] }'




